django/api/urls.py
from django.urls import path
from rest_framework_jwt.views import obtain_jwt_token

from . import views

app_name = 'api'
urlpatterns = [
    path('questions/', views.QuestionListView.as_view(), name='questions'),
    path('questions/hot/', views.HotListView.as_view(), name='hot'),
    path('search/', views.SearchListView.as_view(), name='search'),
    path('question/<int:pk>/answers/', views.AnswerListView.as_view(), name='answers'),
    path(r'auth/', obtain_jwt_token, name='auth'),
]

django/hasker/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework_swagger.views import get_swagger_view

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('swagger/', get_swagger_view(title='Hasker API')),
    path('', include('user.urls')),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.QuestionListView.as_view(), name='index'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('ask-question/', views.QuestionCreateView.as_view(), name='ask'),
    path('tags/', views.TagListView.as_view(), name='tags'),
    path('question/<int:pk>', views.QuestionDetailView.as_view(), name='question'),
    path('question/vote/<int:vote_id>', views.QuestionVoteView.as_view(), name='vote_question'),
    path('answer/vote/<int:vote_id>', views.AnswerVoteView.as_view(), name='vote_answer'),
    path('answer/solution/<int:answer_id>', views.QuestionSolutionView.as_view(), name='answer_solution'),
]

django/main/models.py
from django.conf import settings
from django.db import models, transaction
from django.db.models import F


class TimestampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        abstract = True


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class QuestionManager(models.Manager):
    def hot(self):
        return self.get_queryset().order_by('-rating', '-created_at')

    def new(self):
        return self.get_queryset().order_by('-created_at', '-rating')


class Question(TimestampedModel):
    title = models.CharField(max_length=100, null=False)
    text = models.TextField(null=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)
    tags = models.ManyToManyField(Tag, related_name='questions')
    solution_answer = models.OneToOneField(
        'Answer',
        null=True,
        on_delete=models.CASCADE,
        related_name='solution_answer'
    )

    objects = QuestionManager()

    def __str__(self):
        return self.title

    def set_solution_answer(self, answer):
        self.solution_answer = answer
        return self

    def answers(self):
        return self.answer_set.order_by('-rating', '-created_at')

    def get_tags_names(self):
        return self.tags.values_list('name', flat=True)


class Answer(TimestampedModel):
    text = models.TextField(null=False)
    rating = models.IntegerField(default=0)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

    def mark_as_solution(self):
        if self.question.solution_answer and self.question.solution_answer.id == self.id:
            return self.question.set_solution_answer(None).save()
        return self.question.set_solution_answer(self).save()


class VoteMixin(models.Model):
    value = models.IntegerField(null=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    @classmethod
    def vote(cls, user, entity, value):
        vote = cls.objects.filter(user=user, entity=entity).first()
        if not vote:
            vote = cls(entity=entity, user=user, value=value)
            entity.rating = F('rating') + vote.value
        elif vote.value != value:
            old_value = vote.value
            vote.value = value
            entity.rating = F('rating') - old_value + vote.value
        with transaction.atomic():
            entity.save()
            vote.save()
        entity.refresh_from_db()

    class Meta:
        abstract = True


class AnswerVote(VoteMixin):
    entity = models.ForeignKey(Answer, on_delete=models.CASCADE)


class QuestionVote(VoteMixin):
    entity = models.ForeignKey(Question, on_delete=models.CASCADE)

django/main/forms.py
from django import forms

from django.conf import settings
from hasker.forms import BootstrapForm
from main.models import Question, Answer, Tag


class QuestionForm(BootstrapForm):
    tags = forms.CharField(required=False)

    class Meta:
        model = Question
        fields = ['title', 'text', 'tags']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'rows': 5, 'class': 'form-control'}),
        }

    def clean_tags(self):
        tags = self.cleaned_data.get('tags')
        tags = [] if not tags else [t.strip() for t in tags.split(',')]
        tags = tags[-settings.TAGS_LIMIT:]
        tags_objects = []
        for tag in tags:
            tags_objects.append(Tag.objects.get_or_create(name=tag)[0])
        return tags_objects


class AnswerForm(BootstrapForm):
    class Meta:
        model = Answer
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 5, 'class': 'form-control'}),
        }

django/main/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormMixin

from main.forms import QuestionForm, AnswerForm
from main.models import Question, AnswerVote, Answer, QuestionVote, Tag
from main.utils import QuestionTagSearchHandler, QuestionSearchHandler, Mailer, JSONResponseMixin


class QuestionListView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'questions'
    paginate_by = 20

    def get_queryset(self):
        return Question.objects.hot() if self.is_hot() else Question.objects.new()

    def is_hot(self):
        return self.request.GET.get('tab') == 'hot'


class QuestionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Question
    form_class = QuestionForm

    @property
    def success_url(self):
        return reverse('main:question', args=[self.object.pk])

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.save()
        return super().form_valid(form)


class QuestionDetailView(FormMixin, generic.DetailView):
    model = Question
    form_class = AnswerForm
    paginate_by = 30

    @property
    def success_url(self):
        return reverse('main:question', args=[self.object.pk])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'page_obj': self.get_page(),
            'form': self.get_form(),
        })
        return context

    def get_page(self):
        paginator = Paginator(self.object.answers(), self.paginate_by)
        return paginator.get_page(self.get_page_number())

    def get_page_number(self):
        return self.request.GET.get('page')

    @method_decorator(login_required)
    def post(self, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        return self.form_valid(form) if form.is_valid() else self.form_invalid(form)

    def form_valid(self, form):
        answer = form.save(False)
        answer.question = self.object
        answer.user = self.request.user
        answer.save()
        Mailer.notify(self.request.build_absolute_uri(self.success_url), answer.question.user.email)
        return super().form_valid(form)


class AbstractVoteView(LoginRequiredMixin, JSONResponseMixin, TemplateView):
    model = None
    entity = None

    def post(self, request, vote_id):
        try:
            post_value = int(request.POST.get('value'))
        except ValueError:
            post_value = 1
        value = 1 if post_value > 0 else -1
        entity = get_object_or_404(self.entity, pk=vote_id)
        self.model.vote(request.user, entity, value)
        return self.render_to_json_response(request, data={
            'answer': entity.id,
            'rating': entity.rating
        })


class AnswerVoteView(AbstractVoteView):
    model = AnswerVote
    entity = Answer


class QuestionVoteView(AbstractVoteView):
    model = QuestionVote
    entity = Question


class QuestionSolutionView(LoginRequiredMixin, JSONResponseMixin, TemplateView):
    def post(self, request, answer_id):
        answer = get_object_or_404(Answer, pk=answer_id)
        if request.user.id != answer.question.user.id:
            raise PermissionDenied('You have no access to do this')
        answer.mark_as_solution()
        return self.render_to_json_response(request, data={
            'is_solution': True,
        })


class SearchView(generic.ListView):
    template_name = 'main/search.html'
    context_object_name = 'questions'
    paginate_by = 20
    tag = None

    def get_queryset(self):
        search_handler = self._search_handler
        self.tag = search_handler.get_tag()
        return search_handler.get_question_queryset()

    def get_query_text(self):
        return self.request.GET.get('q')

    @property
    def _search_handler(self):
        query = self.get_query_text()
        return QuestionTagSearchHandler(query) if query.startswith('tag:') else QuestionSearchHandler(query)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['tag'] = self.tag
        return context


class TagListView(JSONResponseMixin, TemplateView):
    def render_to_response(self, context, **response_kwargs):
        tags = [tag.name for tag in Tag.objects.filter(name__contains=self.request.GET.get('term')).all()]
        return self.render_to_json_response(context, data=tags, safe=False)

django/main/templates/main/base.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block scripts %}
    <script src="{% static "main/js/script.js" %}"></script>
{% endblock %}

django/main/templates/main/question_detail.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block title %}Hasker|Question{% endblock %}
{% block content %}
    <h2>{{ question }}</h2>
    <div class="row mt-5">
        <div class="question-vote text-center h2">
            <a href="{% url 'main:vote_question' question.id  %}" class="like text-dark"><i class="fas fa-chevron-up"></i></a>
            <span class="rating">{{ question.rating }}</span>
            <a href="{% url 'main:vote_question' question.id  %}" class="dislike text-dark"><i class="fas fa-chevron-down"></i></a>
        </div>
        <div class="col-11">
            {{ question.text }}
        </div>
    </div>
    <div class="row border-bottom pb-3 mb-3">
        <div class="col-1"></div>
        <div class="col-6">
            {% for tag in question.get_tags_names %}
                <a href="{% url 'main:search' %}?q=tag:{{ tag }}" class="badge badge-success py-1 px-3">{{ tag }}</a>
            {% endfor %}
        </div>
        <div class="col-4">
            {% if question.user.avatar %}
                <img width="50" class="img-thumbnail" src="{{ question.user.avatar.url }}" alt="">
            {% else %}
                <img width="50" class="img-thumbnail" src="{% static 'img/avatar_stub.png' %}" alt="">
            {% endif %}
            <span class="align-middle"><i class="far fa-user"></i> {{ question.user.username }}</span>
        </div>
    </div>
    <div class="answers-list">
        <ul class="list-group list-group-flush">
        {% for answer in page_obj.object_list %}
            <li class="list-group-item question-answer">
                <div class="row mt-5">
                    <div class="answer-vote text-center h2">
                        <a href="{% url 'main:vote_answer' answer.id  %}" class="like text-dark"><i class="fas fa-chevron-up"></i></a>
                        <span class="rating">{{ answer.rating }}</span>
                        <a href="{% url 'main:vote_answer' answer.id  %}" class="dislike text-dark"><i class="fas fa-chevron-down"></i></a>
                        {% if user.is_authenticated and user.id == question.user.id %}
                            <a href="{% url 'main:answer_solution' answer.id %}" class="mark-as-solution">
                                <i class="solution-star {% if answer.question.solution_answer.id == answer.id %}fas{% else %}far{% endif %} fa-star"></i>
                            </a>
                        {% endif %}
                    </div>
                    <div class="col-11">
                        {{ answer.text }}
                    </div>
                </div>
                <div class="row pb-3 mb-3">
                    <div class="col-1"></div>
                    <div class="col-6"></div>
                    <div class="col-4">
                        {% if answer.user.avatar %}
                            <img width="50" class="img-thumbnail" src="{{ answer.user.avatar.url }}" alt="">
                        {% else %}
                            <img width="50" class="img-thumbnail" src="{% static 'img/avatar_stub.png' %}" alt="">
                        {% endif %}
                        <span class="align-middle"><i class="far fa-user"></i> {{ answer.user.username }}</span>
                    </div>
                </div>
            </li>
        {% endfor %}
        </ul>
        <hr>
        {% include 'includes/pagination.html' %}
    </div>

    <form method="post">
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-primary">Answer</button>
    </form>
{% endblock %}

django/main/templates/main/question_form.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block title %}Hasker|Question Filling{% endblock %}
{% block content %}
    <h2>Ask question</h2>
    <form method="post">
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script src="{% static "js/jquery-ui.min.js" %}"></script>
    <script src="{% static "js/jquery.tagsinput.js" %}"></script>
{% endblock %}

django/main/templates/main/search.html
{% extends 'main/base.html' %}
{% block title %}Hasker|Search{% endblock %}
{% block content %}
    {% if tag %}
        <h1>Tag [{{ tag }}] search result</h1>
    {% else %}
        <h1>Search result</h1>
    {% endif %}
    {% include 'main/includes/question_list.html' %}
{% endblock %}