django/api/urls.py
from django.urls import path
from rest_framework_jwt.views import obtain_jwt_token

from . import views

app_name = 'api'
urlpatterns = [
    path('questions/', views.QuestionListView.as_view(), name='questions'),
    path('questions/hot/', views.HotListView.as_view(), name='hot'),
    path('search/', views.SearchListView.as_view(), name='search'),
    path('question/<int:pk>/answers/', views.AnswerListView.as_view(), name='answers'),
    path(r'auth/', obtain_jwt_token, name='auth'),
]

django/hasker/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework_swagger.views import get_swagger_view

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('swagger/', get_swagger_view(title='Hasker API')),
    path('', include('user.urls')),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.QuestionListView.as_view(), name='index'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('ask-question/', views.QuestionCreateView.as_view(), name='ask'),
    path('tags/', views.TagListView.as_view(), name='tags'),
    path('question/<int:pk>', views.QuestionDetailView.as_view(), name='question'),
    path('question/vote/<int:vote_id>', views.QuestionVoteView.as_view(), name='vote_question'),
    path('answer/vote/<int:vote_id>', views.AnswerVoteView.as_view(), name='vote_answer'),
    path('answer/solution/<int:answer_id>', views.QuestionSolutionView.as_view(), name='answer_solution'),
]

django/user/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('user/profile/', views.UserProfileView.as_view(), name='profile'),
]

django/main/models.py
from django.conf import settings
from django.db import models, transaction
from django.db.models import F


class TimestampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        abstract = True


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class QuestionManager(models.Manager):
    def hot(self):
        return self.get_queryset().order_by('-rating', '-created_at')

    def new(self):
        return self.get_queryset().order_by('-created_at', '-rating')


class Question(TimestampedModel):
    title = models.CharField(max_length=100, null=False)
    text = models.TextField(null=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)
    tags = models.ManyToManyField(Tag, related_name='questions')
    solution_answer = models.OneToOneField(
        'Answer',
        null=True,
        on_delete=models.CASCADE,
        related_name='solution_answer'
    )

    objects = QuestionManager()

    def __str__(self):
        return self.title

    def set_solution_answer(self, answer):
        self.solution_answer = answer
        return self

    def answers(self):
        return self.answer_set.order_by('-rating', '-created_at')

    def get_tags_names(self):
        return self.tags.values_list('name', flat=True)


class Answer(TimestampedModel):
    text = models.TextField(null=False)
    rating = models.IntegerField(default=0)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

    def mark_as_solution(self):
        if self.question.solution_answer and self.question.solution_answer.id == self.id:
            return self.question.set_solution_answer(None).save()
        return self.question.set_solution_answer(self).save()


class VoteMixin(models.Model):
    value = models.IntegerField(null=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    @classmethod
    def vote(cls, user, entity, value):
        vote = cls.objects.filter(user=user, entity=entity).first()
        if not vote:
            vote = cls(entity=entity, user=user, value=value)
            entity.rating = F('rating') + vote.value
        elif vote.value != value:
            old_value = vote.value
            vote.value = value
            entity.rating = F('rating') - old_value + vote.value
        with transaction.atomic():
            entity.save()
            vote.save()
        entity.refresh_from_db()

    class Meta:
        abstract = True


class AnswerVote(VoteMixin):
    entity = models.ForeignKey(Answer, on_delete=models.CASCADE)


class QuestionVote(VoteMixin):
    entity = models.ForeignKey(Question, on_delete=models.CASCADE)

django/templates/base.html
{% load staticfiles %}
{% load main_extras %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/fontawesome/css/all.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/jquery.tagsinput.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}"/>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="hasker-container d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm mx-auto">
    <h3 class="my-0 mr-md-auto font-weight-normal"><a href="/" class="badge badge-primary">H</a>asker</h3>
    <form class="form-inline mt-2 mt-md-0 mr-5" action="{% url 'main:search' %}">
        <input class="form-control py-2 border-right-0 border" type="search" name="q" value="{{ request.GET.q }}">
        <span class="input-group-append">
            <button class="btn btn-outline-secondary border-left-0 border" type="submit">
                <i class="fa fa-search"></i>
            </button>
        </span>
    </form>
    {% if user.is_authenticated %}
        <a href="{% url 'user:profile' %}">
            {% if user.avatar %}
                <img width="50" class="img-thumbnail" src="{{ user.avatar.url }}" alt="">
            {% else %}
                <img width="50" class="img-thumbnail" src="{% static 'img/avatar_stub.png' %}" alt="">
            {% endif %}
        </a>
        <div class="d-inline-block ml-2 profile-head">
            <i class="far fa-user"></i>
            <a class="text-dark" href="{% url 'user:profile' %}">{{ user.username }}</a> |
            <a class="text-dark" href="{% url 'user:logout' %}">Logout</a>
        </div>

    {% else %}
        <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-dark" href="{% url 'user:login' %}">Log in</a>
        </nav>
        <a class="btn btn-outline-primary" href="{% url 'user:signup' %}">Sign up</a>
    {% endif %}
</div>

<div class="container">
    <div class="row">
        <div class="col-md-8">
            {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
            <div class="trending">
                <div>
                    <a class="btn btn-outline-success" href="{% url 'main:ask' %}">Ask question</a>
                </div>
                <hr>
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-muted">Trending</span>
                </h4>
                {% question_list_trending %}
            </div>
        </div>
    </div>
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                <h5 class="mb-3 font-weight-normal"><a href="/" class="badge badge-primary">H</a>asker</h5>
                <small class="d-block mb-3 text-muted">© 2018 - 2019</small>
            </div>
        </div>
    </footer>
</div>
<script src="{% static "js/jquery-3.3.1.min.js" %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

django/templates/index.html
{% extends 'base.html' %}
{% block title %}Hasker{% endblock %}
{% block content %}
    <ul class="nav nav-pills">
        <li class="nav-item">
            <a class="nav-link {% if not request.GET.tab %}active{% endif %}" href="{% url 'main:index' %}">New</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if request.GET.tab == 'hot' %}active{% endif %}" href="/?tab=hot">Hot</a>
        </li>
    </ul>
    <hr>
    {% include 'main/includes/question_list.html' %}
{% endblock %}